version: "3.8"

services:
  app:
    image: node
    container_name: linksweb
    restart: on-failure:3
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=db
      - DATABASE_USER=fazt
      - DATABASE_PASSWORD=mypassword
      - DATABASE_NAME=linksdb
      - PORT=8080
    volumes:
      - .:/app
    command: bash -c "npm install && npm run dev"
  